name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot App
        run: mvn clean package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: target/*.jar

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          
          # Copy JAR file to EC2
          scp -o StrictHostKeyChecking=no -i key.pem target/*.jar $USER@$HOST:/home/ec2-user/app.jar

          # SSH into EC2 and restart the app
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST << 'EOF'
            sudo kill $(sudo lsof -t -i:8080) || true
            nohup java -jar /home/ec2-user/app.jar > app.log 2>&1 &
          EOF
